truncate table public.shopify_product_embeddings, public.shopify_product_variants, public.shopify_products restart identity cascade;

insert into public.shopify_products (slug, sku, title, description, category, gender, price_usd, availability, fit, material, care, size_notes, occasion, footwear_width_fit, colorways, images, featured) values
('men-noir-derby', 'VN-M-FT-101', 'Noir Derby', 'Minimal derby in brushed calf leather with refined edge stitching.', 'footwear', 'men', 560, 'in_stock', 'tailored', 'Brushed calf leather', 'Spot clean and condition monthly', 'True to size with structured forefoot', 'work', 'regular', '["Black","Cinder","Espresso"]'::jsonb, '["/assets/footwear-product-01.jpg"]'::jsonb, true),
('men-axis-chelsea', 'VN-M-FT-102', 'Axis Chelsea Boot', 'Sharp-profile Chelsea boot with low stacked heel.', 'footwear', 'men', 640, 'in_stock', 'tailored', 'Polished leather', 'Use neutral cream and cedar trees', 'Slightly narrow instep', 'evening', 'regular', '["Obsidian","Dark Oak","Graphite"]'::jsonb, '["/assets/footwear-product-02.jpg"]'::jsonb, false),
('men-shift-runner', 'VN-M-FT-103', 'Shift Runner', 'Premium runner silhouette with sculpted EVA base.', 'footwear', 'men', 420, 'in_stock', 'relaxed', 'Nappa leather and mesh', 'Wipe clean with damp cloth', 'Comfort fit through toe box', 'travel', 'both', '["Bone","Charcoal","Slate"]'::jsonb, '["/assets/footwear-product-03.jpg"]'::jsonb, true),
('men-carbon-loafer', 'VN-M-FT-104', 'Carbon Loafer', 'Unlined penny loafer with clean apron seam.', 'footwear', 'men', 510, 'low_stock', 'slim', 'Soft calf suede', 'Brush suede and protect from moisture', 'Runs half size large', 'work', 'regular', '["Ash","Black","Taupe"]'::jsonb, '["/assets/footwear-product-04.jpg"]'::jsonb, false),
('men-drift-hiker', 'VN-M-FT-105', 'Drift Hiker', 'Urban hiker with technical sole and matte hardware.', 'footwear', 'men', 590, 'in_stock', 'relaxed', 'Water-resistant nubuck', 'Clean with soft brush and spray protector', 'Extra room at forefoot for layered socks', 'travel', 'wide', '["Black","Fog","Moss"]'::jsonb, '["/assets/footwear-product-05.jpg"]'::jsonb, false),
('men-nightfall-oxford', 'VN-M-FT-106', 'Nightfall Oxford', 'Wholecut oxford with low-profile lace channel.', 'footwear', 'men', 680, 'in_stock', 'tailored', 'Mirror-finish calf leather', 'Polish with soft cloth before wear', 'Structured fit; choose standard size', 'evening', 'regular', '["Black","Merlot","Midnight"]'::jsonb, '["/assets/footwear-product-06.jpg"]'::jsonb, false),
('men-vault-court', 'VN-M-FT-107', 'Vault Court Sneaker', 'Low-top court sneaker with tonal paneling.', 'footwear', 'men', 390, 'in_stock', 'relaxed', 'Full-grain leather', 'Spot clean and air dry', 'Fits true to size', 'travel', 'both', '["Ivory","Ink","Stone"]'::jsonb, '["/assets/footwear-product-07.jpg"]'::jsonb, true),
('men-obsidian-monk', 'VN-M-FT-108', 'Obsidian Monk Strap', 'Single monk strap with sleek buckle profile.', 'footwear', 'men', 600, 'low_stock', 'slim', 'Polished leather', 'Condition leather biweekly', 'Narrow heel cup', 'work', 'regular', '["Obsidian","Chestnut","Smoke"]'::jsonb, '["/assets/footwear-product-08.jpg"]'::jsonb, false),
('men-echo-slip-on', 'VN-M-FT-109', 'Echo Slip-On', 'Minimal slip-on trainer with flexible collar.', 'footwear', 'men', 350, 'in_stock', 'relaxed', 'Stretch knit and suede', 'Hand clean upper with mild soap', 'Comfort stretch around midfoot', 'travel', 'wide', '["Carbon","Sand","Olive"]'::jsonb, '["/assets/footwear-product-09.jpg"]'::jsonb, false),
('men-studio-ankle-boot', 'VN-M-FT-110', 'Studio Ankle Boot', 'Clean ankle boot with concealed side zip.', 'footwear', 'men', 630, 'out_of_stock', 'tailored', 'Satin-finish leather', 'Store with boot trees', 'True to size with firm ankle hold', 'evening', 'regular', '["Black","Cinder","Espresso"]'::jsonb, '["/assets/footwear-product-10.jpg"]'::jsonb, false),
('women-nocturne-heel', 'VN-W-FT-201', 'Nocturne Heel', 'Pointed heel with sculpted arch and soft shine.', 'footwear', 'women', 520, 'in_stock', 'slim', 'Polished calf leather', 'Wipe and polish after wear', 'Runs slightly narrow', 'evening', 'regular', '["Black","Oxide","Bone"]'::jsonb, '["/assets/footwear-product-11.jpg"]'::jsonb, true),
('women-lumen-slingback', 'VN-W-FT-202', 'Lumen Slingback', 'Refined slingback with softened square toe.', 'footwear', 'women', 490, 'in_stock', 'tailored', 'Gloss leather', 'Polish lightly and avoid rain', 'Secure strap with regular fit', 'work', 'regular', '["Ivory","Ink","Rosewood"]'::jsonb, '["/assets/footwear-product-12.jpg"]'::jsonb, false),
('women-ribbon-mule', 'VN-W-FT-203', 'Ribbon Mule', 'Open-back mule with tapered profile.', 'footwear', 'women', 460, 'low_stock', 'slim', 'Suede', 'Use suede brush before storage', 'Best for regular width', 'evening', 'regular', '["Noir","Taupe","Smoke"]'::jsonb, '["/assets/footwear-product-13.jpg"]'::jsonb, false),
('women-arc-ballet', 'VN-W-FT-204', 'Arc Ballet Flat', 'Modern ballet flat with lightly structured vamp.', 'footwear', 'women', 380, 'in_stock', 'relaxed', 'Soft napa leather', 'Spot clean and air dry', 'Comfort fit through forefoot', 'work', 'both', '["Bone","Black","Clay"]'::jsonb, '["/assets/footwear-product-14.jpg"]'::jsonb, true),
('women-veil-court', 'VN-W-FT-205', 'Veil Court Sneaker', 'Minimal court sneaker with tonal stitching.', 'footwear', 'women', 400, 'in_stock', 'relaxed', 'Grain leather', 'Clean with microfiber cloth', 'Roomy fit, ideal for longer wear', 'travel', 'wide', '["Pearl","Sand","Ink"]'::jsonb, '["/assets/footwear-product-15.jpg"]'::jsonb, false),
('women-muse-knee-boot', 'VN-W-FT-206', 'Muse Knee Boot', 'Tall boot with clean shaft and fine seam detail.', 'footwear', 'women', 710, 'in_stock', 'tailored', 'Smooth leather', 'Condition and store upright', 'Regular width, fitted ankle', 'evening', 'regular', '["Black","Chestnut","Cinder"]'::jsonb, '["/assets/footwear-product-16.jpg"]'::jsonb, false),
('women-eclipse-platform', 'VN-W-FT-207', 'Eclipse Platform Sandal', 'Platform sandal with sculpted strap architecture.', 'footwear', 'women', 540, 'low_stock', 'tailored', 'Lamb leather', 'Store in dust bag', 'Adjustable straps suit regular and wide feet', 'evening', 'both', '["Onyx","Bronze","Ivory"]'::jsonb, '["/assets/footwear-product-17.jpg"]'::jsonb, false),
('women-atelier-loafer', 'VN-W-FT-208', 'Atelier Loafer', 'Soft loafer with low stacked heel and matte trim.', 'footwear', 'women', 450, 'in_stock', 'relaxed', 'Italian calf suede', 'Brush suede and avoid heavy moisture', 'Wider forefoot comfort', 'work', 'wide', '["Mink","Black","Stone"]'::jsonb, '["/assets/footwear-product-18.jpg"]'::jsonb, false),
('women-nova-ankle-boot', 'VN-W-FT-209', 'Nova Ankle Boot', 'Ankle boot with internal zip and modern heel block.', 'footwear', 'women', 620, 'out_of_stock', 'slim', 'Polished leather', 'Protect from water and polish monthly', 'Narrow profile; size up for wide feet', 'evening', 'regular', '["Black","Oxblood","Smoke"]'::jsonb, '["/assets/footwear-product-19.jpg"]'::jsonb, false),
('women-zenith-runner', 'VN-W-FT-210', 'Zenith Runner', 'Performance-inspired runner with luxe finish.', 'footwear', 'women', 430, 'in_stock', 'relaxed', 'Technical knit and leather', 'Wipe clean and air dry', 'Adaptive upper supports regular and wide fits', 'travel', 'both', '["Pearl","Graphite","Sage"]'::jsonb, '["/assets/footwear-product-20.jpg"]'::jsonb, true);